title: MiVOZ
description: "Ayudando a mejorar colaborativamnte"
social:
  - title: twitter
    url: https://twitter.com/MiVozUy
  - title: facebook
    url: https://facebook.com/MiVozUy
markdown: kramdown
permalink: pretty