title: MiVoz
description: "Ahora tienes voz, ¡úsala!"
social:
  - title: twitter
    url: https://twitter.com/MiVozUy
  - title: facebook
    url: https://facebook.com/MiVozUy
markdown: kramdown
permalink: pretty
